spring:
  application:
    name: Config
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_CONFIG_URI}
          username: WilliamBC24
          password: ${GITHUB_PASS}

server:
  port: 8100

#eureka:
# client:
#   service-url:
#     defaultZone: ${EUREKA_SERVER}

logging:
  level:
    org.springframework.cloud: DEBUG
