spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    import: "optional:configserver:${CONFIG_URI}"

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
    service:
      authservice: debug