services:
  # mysql:
  #   image: mysql:9.1.0
  #   restart: always
  #   networks:
  #     - microservice
  #   ports:
  #     - "3906:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 30s
  #     retries: 3  
  
  eureka:
    build: 
      context: ./Eureka
    restart: always
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    networks:
      - microservice
    volumes:
      - ./src:/eureka/src
      - ./build:/eureka/build      
    environment:
     CONFIG_URI: ${CONFIG_URI}


  gateway:
    build:
      context: ./Gateway
    restart: always
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - microservice
    volumes:
      - ./src:/gateway/src
      - ./build:/gateway/build
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}  
      CONFIG_URI: ${CONFIG_URI}
    depends_on:
      - eureka   
      - config

  config:
    build:
      context: ./Config
    restart: always
    ports:
      - "${CONFIG_PORT}:${CONFIG_PORT}"     
    networks:
      - microservice
    volumes:
      - ./src:/config/src
      - ./build:/config/build
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}
      GITHUB_PASS: ${GITHUB_PASS}
      GITHUB_CONFIG_URI: ${GITHUB_CONFIG_URI}  

  microservice:
    build:
      context: ./Microservice
    restart: always
    ports:
      - "${MICROSERVICE_PORT}:${MICROSERVICE_PORT}"
    networks:
      - microservice
    volumes:
      - ./src:/microservice/src
      - ./build:/microservice/build
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
      CONFIG_URI: ${CONFIG_URI}
    depends_on:
      - mysql
      - eureka
      - config


networks:
  microservice:
    driver: bridge

volumes:
  mysql_data:
