services:
  postgres:
    image: postgres:13
    restart: always
    networks:
      - microservice
    ports:
      - "${USER_DB_OUTER_PORT}:${USER_DB_INNER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${USER_DB_DATABASE}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}

  # mongo:
  #   image: mongo:8.0.4
  #   restart: always
  #   networks:
  #     - microservice
  #   ports:
  #     - "${MSG_DB_OUTER_PORT}:${MSG_DB_INNER_PORT}"     
  #   volumes:
  #     - mongo_data:/data/db 
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MSG_DB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MSG_DB_ROOT_PASSWORD}
  
  # eureka:
  #   build: 
  #     context: ./Eureka
  #   restart: always
  #   ports:
  #     - "${EUREKA_PORT}:${EUREKA_PORT}"
  #   networks:
  #     - microservice
  #   volumes:
  #     - ./src:/eureka/src
  #     - ./build:/eureka/build      
  #   environment:
  #    CONFIG_URI: ${CONFIG_URI}


  # gateway:
  #   build:
  #     context: ./Gateway
  #   restart: always
  #   ports:
  #     - "${GATEWAY_PORT}:${GATEWAY_PORT}"
  #   networks:
  #     - microservice
  #   volumes:
  #     - ./src:/gateway/src
  #     - ./build:/gateway/build
  #   environment:
  #     EUREKA_SERVER: ${EUREKA_SERVER}  
  #     CONFIG_URI: ${CONFIG_URI}
  #   depends_on:
  #     - eureka   
  # #     - config

  # config:
  #   build:
  #     context: ./Config
  #   restart: always
  #   ports:
  #     - "${CONFIG_PORT}:${CONFIG_PORT}"     
  #   networks:
  #     - microservice
  #   volumes:
  #     - ./src:/config/src
  #     - ./build:/config/build
  #   environment:
  #     EUREKA_SERVER: ${EUREKA_SERVER}
  #     GITHUB_PASS: ${GITHUB_PASS}
  #     GITHUB_CONFIG_URI: ${GITHUB_CONFIG_URI}  

  authservice:
    build:
      context: ./AuthService
    restart: always
    ports:
      - "${AUTHSERVICE_PORT}:${AUTHSERVICE_PORT}"
    networks:
      - microservice
    volumes:
      - ./src:/authservice/src
      - ./build:/authservice/build
    environment:
      DB_URL: ${USER_DB_URL}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
      CONFIG_URI: ${CONFIG_URI}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
    depends_on:
      - postgres
      # - eureka
      # - config

  # nodefront:
  #   build: 
  #     context: ./NodeFrontEnd
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   # environment:
  #   #   NODE_ENV: production
  #   restart: always

networks:
  microservice:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
