services:
  mysql:
    image: mysql:latest
    restart: always
    networks:
      - microservice
    ports:
      - "3906:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3  
  
  eureka:
    build: 
      context: ./Eureka
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservice
    volumes:
      - ./src:/eureka/src
      - ./build:/eureka/build      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
      interval: 30s
      retries: 3  

  gateway:
    build:
      context: ./Gateway
    restart: always
    ports:
      - "8080:8081"
    networks:
      - microservice
    volumes:
      - ./src:/gateway/src
      - ./build:/gateway/build
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}  
    depends_on:
      - eureka    

  microservice:
    build:
      context: ./Microservice
    restart: always
    ports:
      - "8081:8080"
    networks:
      - microservice
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_SERVER: ${EUREKA_SERVER}
    volumes:
      - ./src:/microservice/src
      - ./build:/microservice/build
    depends_on:
      - mysql
      - eureka


networks:
  microservice:
    driver: bridge

volumes:
  mysql_data:
