spring:
  application:
    name: message-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: ${URI}
#      database: ${DB}
#      username: ${USERNAME}
#      password: ${PASSWORD}
#      host: ${HOST}
#      port: ${PORT}
#      authentication-database: ${AUTH_DB}

server:
  port: 8081