spring:
  application:
    name: message-service
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_DB}
#      username: ${USERNAME}
#      password: ${PASSWORD}
#      host: ${HOST}
#      port: ${PORT}
#      authentication-database: ${AUTH_DB}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
    service:
      authservice: debug

server:
  port: 8081