spring:
  application:
    name: message-service
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_DB}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG

server:
  port: 8081
