spring:
  application:
    name: message-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: ${URI}
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
