spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
#            sonbui.com is not needed as /front and /gateway are both on it
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  config:
    import: "optional:configserver:"

server:
  port: 8090

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"
