spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  config:
    import: "optional:configserver:${CONFIG_URI}"

server:
  port: 8090

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
    service:
      gateway: DEBUG