spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/authservice/**
          filters:
            - StripPrefix=1
  config:
    import: "optional:configserver:${CONFIG_URI}"


server:
  port: 8090
