spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: message-service
          uri: http://localhost:8081
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
        - id: message-service-ws
          uri: ws://localhost:8081/ws
          predicates:
            - Path=/message/ws/**
          filters:
            - StripPrefix=1
