spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authservice
          uri: http://auth-service-service:8080
          predicates:
            - Path=/authservice/**
          filters:
            - StripPrefix=1
  config:
    import: "optional:configserver:${CONFIG_URI}"

server:
  port: 8090

