spring:
  application:
    name: Gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
        - id: Microservice
          uri: lb://Microservice
          predicates:
            - Path=/microservice/**
  config:
    import: "optional:configserver:${CONFIG_URI}"

server:
  port: 8090
