spring:
  application:
    name: Microservice
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    username: dev_local
    password: Abc123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 20000
      auto-commit: true
      pool-name: sonbui
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  servlet:
    multipart:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080
