name: Build & Push Changed Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for change detection

      - name: Get Changed Folders
        id: changed_files
        run: |
          echo "Detecting changed directories..."
          
          # Define relevant service folders
          SERVICES=("auth-service" "config" "eureka" "gateway" "node")

          # Get changed directories from the last commit
          changed_dirs=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $1}' | sort -u | uniq | grep -E "$(IFS='|'; echo "${SERVICES[*]}")" || true)

          # Ensure script doesn't break if no services changed
          if [[ -z "$changed_dirs" ]]; then
            echo "No relevant services changed. Skipping build."
            echo "changed_dirs=" >> $GITHUB_ENV
            echo "changed_dirs=" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Changed directories: $changed_dirs"

          # Save to GitHub outputs for later steps
          echo "changed_dirs=$(echo $changed_dirs | tr '\n' ' ')" >> $GITHUB_ENV
          echo "changed_dirs=$(echo $changed_dirs | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build & Push Changed Services
        if: env.changed_dirs != ''
        run: |
          DOCKER_USER="${{ secrets.DOCKER_USERNAME }}"

          for folder in $changed_dirs; do
            if [ -f "$folder/Dockerfile" ]; then
              IMAGE_NAME="$DOCKER_USER/$folder:latest"

              echo "==============================="
              echo "Building image for $folder"

              docker buildx build \
                --cache-from=type=registry,ref=$IMAGE_NAME \
                --cache-to=type=inline \
                --tag $IMAGE_NAME \
                --push \
                $folder
            else
              echo "Skipping $folder - No Dockerfile found."
            fi
          done
