name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build & Push Each Service with Cache
        run: |
          DOCKER_USER="${{ secrets.DOCKER_USERNAME }}"
          
          for folder in $(find . -type f -name "Dockerfile" -exec dirname {} \;); do
            folder_name=$(basename $folder)
            image_name="$DOCKER_USER/$folder_name:latest"

            echo "==============================="
            echo "Building image for $folder_name"

            docker buildx build \
              --cache-from=type=registry,ref=$image_name \
              --cache-to=type=inline \
              --tag $image_name \
              --push \
              $folder
          done
