name: Learning

on:
    push:
        branches:
            - main
    workflow_dispatch:        

jobs:
    build:
        name: Build Image              
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build image
              run: |
                name=secretRepo/folderName:latest
                echo "Building image"        
                docker build -t $name --cache-from=type=registry,ref=$name folderWithChanges
                echo "Pushing image"
                docker push $name

                # write CI for dev branch, for tests
                # write CD for main branch, for deployment