name: Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Find and Build All Dockerfiles
        run: |
          repo_name="prod"

          for folder in $(find . -type f -name "Dockerfile" -exec dirname {} \;); do
            folder_name=$(basename $folder)
            image_name="$repo_name/$folder_name:latest"
            
            echo "Building image for $folder_name"
            docker build -t $image_name --cache-from=type=registry,ref=$image_name $folder

            echo "Pushing image for $folder_name"
            docker push $image_name
          done
